### ISSUE TITLE
Alerts for drastically rising resources

### ISSUE THREAD

**Issue by shubhamc183** [samber/awesome-prometheus-alerts#143]
Can we have alerts for catching a drastic increase in resources like memory, cpu, and disk?

CASE 1
- Host out of memory is set at 80%
- Memory is rising 10%(of total) every 10mins and will reach 80% in 30 mins.
- An alert that could have caught this trend.

CASE 2
- `/var` out of disk space is set at 80%
- Unusually application is writing heavy logs 5%(of total) in 1 hour instead of 1%(of total) in 24 hours.
- An alert to notify this trend.

**Comment by samber** [comment]
Hi @shubhamc183,

Those alerts already exist. Please take a look on following section => https://awesome-prometheus-alerts.grep.to/rules#host-and-hardware

Feel free to change thresholds, since it really depends on your application, "normal" load, etc...

You can mix some alerts using `and` keyword in expressions.
