### ISSUE TITLE
Issue with HAProxy Alerts

### ISSUE THREAD

**Issue by mr-karan** [samber/awesome-prometheus-alerts#162]
There's an issue with:

- `3.3.6. HAProxy backend connection errors`
- `3.3.7. HAProxy server response errors`
- `3.3.8. HAProxy server connection errors`

The issue is common to all three metrics: They are used as a `%` calculation however all of these metrics are of type `Counter`. A `counter` is always increasing, so doing  a `rate` on it gives a per-second averaged value. However this is an absolute value and not a percentage one.

It's possible to get a % value for `HAProxy server response errors` using `haproxy_server_response_errors_total` and dividing it by `haproxy_server_http_responses_total`. However for the rest 2 metrics, there isn't any metric available in [prometheus/haproxy-exporter](https://github.com/prometheus/haproxy_exporter) to give this value.

I can send a fix for `3.3.7` but unsure what to do with other alerts. They are misleading and the docs should point it out at least.

**Comment by samber** [comment]
Hi @mr-karan 

I see what you mean.

I checked on exporter source code. It seems those metrics are not exported, as the exporter just parses the csv `/stats` endpoint and some data are missing data.

I just made a fix:
- use `haproxy_server_http_responses_total` when possible
- update alert description+query otherwise

https://github.com/samber/awesome-prometheus-alerts/commit/9f144acb3058b6386497f91eb8b4d72e982c2b66
